### ISSUE TITLE
Styling -- is it possible?

### ISSUE THREAD

**Issue by brutto** [n3-charts/line-chart#176]
Can i style generated graphs? Fo rexample labels on axis too small for me. Or tooltip.

**Comment by willynilly** [comment]
How can we change the tooltip text color from white to black?

**Comment by chaosmail** [comment]
Hi,
you can change those things easily in your css, simply put
```css
.scrubberText {
  font-size: 14px;
}
```
to style the tooltip text (scrubber mode) or
```css
.legendText {
  font-size: 14px;
}
```
to stype the legend description. Hope that helps.

Best,
Christoph
