### ISSUE TITLE
Expose font-family property for labels / tooltips

### ISSUE THREAD

**Issue by nicolabortignon** [n3-charts/line-chart#312]
Would be great to expose the fontFamily property for the axes and tooltips.

**Comment by chaosmail** [comment]
You can style this via CSS but maybe you will have to use the `!important` priority

**Comment by nicolabortignon** [comment]
Which css class should I try to extend in order to keep the scope inside the library ?

**Comment by nicolabortignon** [comment]
With this style: 

```css
.chart *[style] {
  font-size: 11px !important;
  font-family: "Impact", Helvetica, Arial, sans-serif !important;
  -webkit-font-smoothing: antialiased;
}
```

I have this results: 

 
![screen shot 2015-08-26 at 2 46 22 pm](https://cloud.githubusercontent.com/assets/883459/9507218/70f2d7ae-4c01-11e5-8054-1a5dac0da784.png)

In order to style the legend as well i need to use something like: 
```css
.chart *[font-family] {
  font-family: "Impact", Helvetica, Arial, sans-serif !important;
}
```

The reason why is that the inlining of the css is sometimes done with style=""  and sometimes with just attribute-name="value".

Worth checking if is possible to have a consistent way to express inline style.
