### ISSUE TITLE
Axis GRID

### ISSUE THREAD

**Issue by nishadotcom** [n3-charts/line-chart#367]
Can we change the grids line color????
and can we display the grid(Y/X) line for few labels alone????

Regards,
nishadotcom

**Comment by pihomeserver** [comment]
Here is how i did for grid lines :
```css
.tick line {
	stroke: #f00
}
```

I try now to change the axis line too
