### ISSUE TITLE
\a in compiled css url

### ISSUE THREAD

**Issue by darrinholst** [n3-charts/line-chart#512]
`build/LineChart.css` has a few url declarations with inline svg containing `\a`s...

``` css
    .chart-legend .item.dashed-line > .icon {
      background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' style='fill: white;' width='10' height='10'>\a         <g style=\"stroke: white; fill: none; stroke-dasharray: 4px,2px;\">\a           <path d='M0,6 L10,6'/>\a         </g>\a       </svg>"); }
```

From what I could tell it's from those selectors that use newlines like [here](https://github.com/n3-charts/line-chart/blob/master/src/styles/_legend.scss#L47). 

I'm not sure what `\a` means  (guessing it's a unicode escape string for a newline) and it wasn't a problem until a comical series of updates involving webpack, css-loader, postcss-modules-local-by-default and css-selector-tokenizer which eventually got to [this code](https://github.com/css-modules/css-selector-tokenizer/commit/90613f2ae72993ac94a0f72890ba09715463830a) that converted them back to newlines which ended up turning my css in to...

``` css
    .chart-legend .item.dashed-line > .icon {
      background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' style='fill: white;' width='10' height='10'>
         <g style=\"stroke: white; fill: none; stroke-dasharray: 4px,2px;\">
           <path d='M0,6 L10,6'/>
         </g>
       </svg>"); }
```

in which any css after that point got ignored.

So I guess my question is there a way to have sass strip the new lines?
